wandb_version: 1

GB_kernel_size:
  desc: null
  value: 3
GB_sigma:
  desc: null
  value: 0.75
_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1650063128
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      4: 3.9.5
      5: 0.12.14
      8:
      - 5
backbone_type:
  desc: null
  value: resnet18
batch_size:
  desc: null
  value: 128
center_bias_weight:
  desc: null
  value: null
distracting_block:
  desc: null
  value: layer3
epochs:
  desc: null
  value: 30
eval_metric_name:
  desc: null
  value: accuracy
feature_channels_num:
  desc: null
  value: 1280
feature_h:
  desc: null
  value: 14
feature_target_layer:
  desc: null
  value:
  - layer3.1.conv1
  - layer3.1.conv2
  - layer3.0.conv2
  - layer4.0.conv2
feature_w:
  desc: null
  value: 14
learning_rate_D:
  desc: null
  value: 0.0001
learning_rate_R:
  desc: null
  value: 0.0001
momentum_D_backbone:
  desc: null
  value: 0.001
pretrained:
  desc: null
  value: true
seed:
  desc: null
  value: 42
wrap_size:
  desc: null
  value: 224
