backbone_type: resnet18
feature_target_layer:
  - layer3.1.conv1
  - layer3.1.conv2
  - layer3.0.conv2
  - layer4.0.conv2
feature_channels_num: 1280 # 256 + 256 + 256 + 512
feature_h: 14
feature_w: 14
distracting_block: layer3
pretrained: True
GB_kernel_size: 3
GB_sigma: 0.4
batch_size: 256
epochs: 100
wrap_size: 224
seed: 42
save_dir: ./experiments/7
eval_metric_name: accuracy_ten
momentum_D_backbone: 0.00002
wandb_project: 542_exp_no_l1
learning_rate_D: 0.00002
learning_rate_R: 0.00005
weight_decay_R: 1e-18
L1_D: 0.1
save_summary_steps: 100
data_dir: ./AVA
amp: False
